# Generated by Django 3.2.6 on 2021-08-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(choices=[('withscrapy.process.start_scrapy_ecommerce', 'start_scrapy_ecommerce')], max_length=50, verbose_name='Process Name')),
            ],
        ),
    ]
